### PR TITLE
more commands, libgit2-1.3.0

### PR DESCRIPTION
**Pull request by petersalomonsen**
Implementing new commands, and upgrading to libgit2-1.3.0. Commands additions are also added to https://github.com/libgit2/libgit2/pull/5609

- git reset
- git checkout -b (create branch)
- git status --ahead-behind
- show conflicts on git status
- conflict resolution
- merge commits when in merge state
- upgrading to libgit2-1.3.0

#30

### CODE REVIEW

**Comment by petersalomonsen** [comment]
@ciesielskico

this seems to work fine for reset:

https://github.com/petersalomonsen/wasm-git/pull/36/files#diff-d870dd4eac99820b9fd1852534376c9c8189449f5153b23d89c1201df531142fR122

**Comment by petersalomonsen** [comment]
creating of new branch:

https://github.com/petersalomonsen/wasm-git/pull/36/files#diff-d870dd4eac99820b9fd1852534376c9c8189449f5153b23d89c1201df531142fR137

**Comment by ciesielskico** [comment]
I've given this a go and it looks great, I was able to make a commit and get the correct ahead/behind status.
I also was able to checkout a new branch, although when I reload the app I get the following output. 
It happens when I call `git status`.

image

**Comment by ciesielskico** [comment]
While the above branch has been checked out locally and doesn't exist on the remote, interestingly I also get the error also when checking out a branch that definitely exists on the remote

image

**Comment by petersalomonsen** [comment]
I've added a new test case for checking out a branch after clone https://github.com/petersalomonsen/wasm-git/pull/36/files#diff-d870dd4eac99820b9fd1852534376c9c8189449f5153b23d89c1201df531142fR151

For now this fails, because the branch is never actually pushed to the server, since currently the push command only push to master ( see https://github.com/petersalomonsen/wasm-git/blob/master/libgit2patchedfiles/examples/push.c#L36 ).

So I will fix so that also other branches than master can be pushed.

**Comment by ciesielskico** [comment]
Hmm but assuming one just creates a branch locally but after 5 minutes changes his mind and wants to delete it, for those cases I wouldn't want the branch to be published immediately. 

I think what's breaking here is something in the `git status` logic, and since this started happening after you added ahead/behind I'm assuming that specific check causes a problem.

**Comment by petersalomonsen** [comment]
ohh. yeah the `error2:` message is not really relevant. It's because it cannot find the remote branch, and then it's no point to show ahead/behind info. I've removed this error2 message now.

Also I've made it so that `push` now pushes the current checked out branch, and not only master ( https://github.com/petersalomonsen/wasm-git/pull/36/files#diff-1cc4dda9486e18ae98211343da400e4e188af4c370bf6d22844f72a68180ce00R36 )

The branch is not published before you push, not sure if I understood why you worry the branch will be published immediately.

**Comment by ciesielskico** [comment]
Misunderstanding on my side, I thought you meant pushing the newly created branches immediately.
Anyway, looks like the `error2` error is gone now, works good!
Will take a look at pushing branches tomorrow at the earliest.

**Comment by petersalomonsen** [comment]
now also libgit2-1.3.0 seems ok

**Comment by ciesielskico** [comment]
Getting this now when running `./build.sh Release`. 
I have also run `./setup.sh` after pulling latest changes, so not sure what's wrong

image

**Comment by ciesielskico** [comment]
Actually nevermind, I've removed the libgit folders and ran setup.sh again and that did the trick

**Comment by ciesielskico** [comment]
But it seems like git reset stopped worked.

I've tried passing both `HEAD` and the current branche's name and I'm pretty sure that used to work, but now `git status` still says 1 changed file. I think I noticed that that also didn't work before the last commit after all.

**Comment by petersalomonsen** [comment]
yeah, git push will only push the branch you're currently checked into. do you need pushing a branch other than the one you are in?

git reset is now only in default mode. libgit2 supports soft and hard reset too, but I've only exposed the default mode which means that you will see that if you're changes since the reset position will be uncommitted / unstaged. in my test I check that git log has changed to the commit before: https://github.com/petersalomonsen/wasm-git/pull/36/files#diff-d870dd4eac99820b9fd1852534376c9c8189449f5153b23d89c1201df531142fR138

see explanation of git reset modes here: https://git-scm.com/docs/git-reset#Documentation/git-reset.txt-emgitresetemltmodegtltcommitgt

which ones do you need?

**Comment by ciesielskico** [comment]
Ah right, I didn't even think about trying to push without any parameter. No that's right, pushing the current branch is completely fine and enough.

About git reset i guess I was expecting it to run with --hard, I'm just trying to recreate a "discard all changes" option, similar to VSCode. Meaning after running it i would expect all changes to files to be reset. 
Sorry if I didn't make myself clear enough there.

**Comment by petersalomonsen** [comment]
@ciesielskico now you can try `reset --hard`

**Comment by ciesielskico** [comment]
Thanks, that works great, now all changed files are reset and the user has a clean slate. git push works great, too.

Finally, I also got around into giving `git status` a deeper look and while the "ahead" count is right I don't think the "behind" count is being calculated.

I've pushed a commit to the repo from another machine and when doing `git fetch origin` and `git status` it still says 0 behind, even though I see that git fetch indeed downloads something.

**Comment by petersalomonsen** [comment]
are you in another branch than the master branch? maybe it's because tracking information is missing in `.git/config`. See in the test here https://github.com/petersalomonsen/wasm-git/pull/36/files#diff-d870dd4eac99820b9fd1852534376c9c8189449f5153b23d89c1201df531142fR172 where I add info about the remote for the testbranch to set up tracking. Does that help?

**Comment by ciesielskico** [comment]
Yes, I'm on branch `kind-of-working`. 
I'm doing a `git fetch origin` everytime I reload the app, but I'm guessing I need to call something else? 

I tried calling different variations of `git fetch kind-of-working` but I'm getting a `unsupported URL protocol` error

**Comment by petersalomonsen** [comment]
ok so it seems that checking out does not set up tracking to remote (as there is not entry for you `kind-of-working` branch in `.git/config`).

I've added to checkout so that it sets up remote tracking when checking out a branch after cloning. You can see the test-case here: https://github.com/petersalomonsen/wasm-git/pull/36/files#diff-d870dd4eac99820b9fd1852534376c9c8189449f5153b23d89c1201df531142fR160

( the test verifies that `.git/config` contains an entry for the checked out branch ).

currently only supporting remote named `origin`.

**Comment by ciesielskico** [comment]
Sorry for the late reply. That actually worked quite well. I'm correctly informed of how many commits I am behind now.
But it seems that this in turn broke creating a new branch.
This is what I get currently when creating a new branch (which I'm pretty sure used to work previously):

```
const branch = 'newtestbranch';
lg.callAndCaptureOutput(['checkout', '-b', branch])
```

image

**Comment by petersalomonsen** [comment]
I was able to reproduce your error if trying to create a new branch from a repo that was not cloned, but created locally. Since then there is no remote tracking info, and the checkout command is not able to find the remote.

I've added a test case that reproduces this scenario here: https://github.com/petersalomonsen/wasm-git/pull/36/files#diff-d870dd4eac99820b9fd1852534376c9c8189449f5153b23d89c1201df531142fR186

and I've also changed the implementation of checkout.c so that it doesn't throw the error when there's no remote tracking branch.

**Comment by ciesielskico** [comment]
This repo definitely is cloned and not created locally on my machine. But anyway, your last commit seems to have fixed it, I'm able to create branches again. Thanks!

**Comment by petersalomonsen** [comment]
added simple printing of conflicts: https://github.com/petersalomonsen/wasm-git/pull/36/files#diff-c5a485586533a98b409ede6527f06b52f352e52231885135a0ec406576c19ae9R127

**Pull request merged**
