### PR TITLE
Asyncify emscriptenhttp transports

### PR DESCRIPTION
**Pull request by happybeing**
It took me a while to figure out how get the mocha tests to wait for the `Module.onRuntimeInitialized()`, but I've now added a test (`npm run test-browser-async`) very similar to the you created for a webworker. To use it you will first need to build with `./build.sh Debug-async` or `./build.sh Release-async`).

I haven't squashed the commit history as it is very clean, but I believe you can do this when merging (at least on github) if you need it. Let me know if that's not what you need.

Thanks very much for your help in getting this far. I'm still looking at options, but it is good to know I have one in `wasm-git` that should cover all my project's needs for the short to medium term.

### CODE REVIEW

**Comment by petersalomonsen** [comment]
thanks! this looks promising. In order to be able to merge this your test should also be added to [.travis.yml](https://github.com/petersalomonsen/wasm-git/blob/master/.travis.yml) so that it is run in the test pipeline. Also seeing that the pipeline fails because of some syntax error.

Regarding squashing I normally do it before merge using `git rebase -i origin/master` (`pick` the first commit, and set the rest to `squash`) followed by a force push. By squashing before merge it's also possible to review the commit comment.

Also I see that for nodejs it should be possible to have an option of skipping the use of atomics and a separate worker with the async support. I can look into that later if you don't want to spend time on it, but that would of course be a bonus when using from nodejs ( I still want to keep the atomics and separate worker for the regular build, but it would be good to have the option with asyncify also for nodejs ).

most important though is to make the tests pass in travis.

**Comment by happybeing** [comment]
@petersalomonsen I'm not familiar with CI at all yet so the messages don't mean much to me, here: https://travis-ci.com/github/petersalomonsen/wasm-git/builds/212062276.

I've just run "./build.sh" locally on this branch and it completes without issue. The errors look as if they relate to python which I don't believe I've touched so I'm not sure how to debug this.

**Comment by petersalomonsen** [comment]
ok I tried to create a simple PR only changing the readme, and it seems like that build is failing too. So then it has nothing to do with your changes, and probably something related to recent versions of the travis setup. I'll check it out and let you know.

**Comment by petersalomonsen** [comment]
ok it seems like travis was using xenial (ubuntu 16.04) by default, so had to change it to the latest 20.04. If you can add the following changes to your PR: https://github.com/petersalomonsen/wasm-git/pull/19/commits/6da8987bb9999803a5a534a757495c9d1c719b6f

then it should be able to go on. My "Update readme" PR passed now.

**Comment by happybeing** [comment]
@petersalomonsen I've not changed `.travis.yml` yet, just pushed your commit. The build now completes as far as `npm run test` but fails in `npm run test-browser` but I don't understand why.

If I run this locally it is fine. The error says that `Asyncify` is referenced in the `lg2.js` built with `./build.sh` but that's not the case for me locally. Looking at the files changed in the PR I don't see where this is being introduced.

Can you run `./build.sh` and check your `lg2.js` for 'Asyncify'. It isn't present in mine.

**Comment by petersalomonsen** [comment]
sorry for the delay. I spent some time now trying to troubleshoot this, and found that the reason you don't get this error locally is that you don't start from scratch as the pipeline does. In `travis.yml` you'll see that the pipeline runs `setup.sh` which will copy files from the `libgit2patchedfiles` folder. Then it will also copy your `emscriptenhttp-async.c` file which will then be included in the non-async build, and that's why it says `Asyncify is not defined`.

To reproduce the error locally you can remove the `libgit2` folder. Run `setup.sh` again, and then build (without async) and run the regular `test-browser`.

Another thing: I think we should also include the async build in the npm distribution. And so the output files of the async build should be called  e.g. `lg2-async.js` / `lg2-async.wasm`. What do you think?

**Comment by happybeing** [comment]
Ah, thanks. My `build.sh` tries to handle this but I didn't understand quite enough. I suggest I modify `build.sh` to remove `emscriptenhttp-async.c` if present, so that `setup.sh` can copy everything as now and we can leave the `emscriptenhttp-async.c` where they are. What do you think?

I wondered about building `lg2-async.js` but at the time didn't think you'd want it in the distribution. If we do this, I need to make sure that `lg2-async.js` will load `lg2-async.js`. I'm guessing this is a matter of updating the makefile(s) to add a new target. 

Then it would make sense to change `build.sh` to offer a default that builds both sync and async for release, plus an argument for sync or async, say `build.sh [--debug] [sync|async]`. Let me know what would make most sense. Do you think 'sync' and 'async' or would 'webworker' and 'browser' be better for the CLI?

I'd prefer not to mess with the makefiles but can do the rest. Please let me know if the above is ok or how else you think it should be.

**Comment by petersalomonsen** [comment]
yeap, removing `emscriptenhttp-async.c` if present sounds ok.

i think `sync` and `async` is better than `worker` vs `browser` since the `async` could also be relevant in nodejs.

Regarding including it into the build, that can also be done that in a later commit, and not do everything in this PR. As you say it would probably involve some tweaking of the Makefiles, and we can save that for later if it's too much to look into now.

If we don't include it into the build, then we should at least add a travis job running the async test. It's possible to use the `matrix` keyword to add multiple jobs in `travis.yml`

I believe it should look something like this:

```

matrix:
  include:
    - language: node_js
      name: "default"
      dist: focal
      os: linux
      node_js:
        - 14

      install:
        - npm install
        - sh setup.sh
        - git clone https://github.com/emscripten-core/emsdk.git
        - cd emsdk
        - ./emsdk install latest
        - ./emsdk activate latest
        - cd ..
        - source ./emsdk/emsdk_env.sh
        - cd emscriptenbuild
        - ./build.sh
        - cd ..
      script:
      - |
        set -e
        npm run test
        npm run test-browser
        ./preparepublishnpm.sh  
        PACKAGEFILE=`npm pack | tail -n 1`
        tar -xvzf $PACKAGEFILE
        rm test-browser/lg2.*
        echo "run browser tests with npm package"
        cp package/lg2.* test-browser/
        npm run test-browser
    - language: node_js
      name: "asyncify"
      dist: focal
      os: linux
      node_js:
        - 14

      install:
        - npm install
        - sh setup.sh
        - git clone https://github.com/emscripten-core/emsdk.git
        - cd emsdk
        - ./emsdk install latest
        - ./emsdk activate latest
        - cd ..
        - source ./emsdk/emsdk_env.sh
        - cd emscriptenbuild
        - ./build.sh Release-async
        - cd ..
      script:
      - |
        set -e
        npm run test-browser-async
```

**Comment by happybeing** [comment]
The fix to `build.sh` works so I'm trying to update `.travis.yml`. I haven't used `travis` so have installed it and looked for docs on 'matrix' keyword but can't find them. So trying `travis lint` on your suggestion above, is a bit odd:
```
$ /usr/local/bin/travis lint
Warnings for .travis.yml:
[x] [warn] on jobs.include.node_js: unexpected sequence, using the first value (14)
[x] [warn] on jobs.include.node_js: unexpected sequence, using the first value (14)
```
It appears not to like the `-14` in either build spec. If I remove both the lines `   - 14` it passes lint. Same if I also remove both `node_js: /   - 14`. If I leave just the first `  - 14` I get one warning etc. 

So I pushed `.travis.yml` as your suggestion, but with the to `   - 14` lines removed but that failed with what look like node errors.

So ignoring the `travis lint` warnings I went with what you suggested and it passes!

**Pull request merged**
